name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Checkout the repository to the GitHub Actions runner
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    # Get Flutter SDK
    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.7'

    # Cache Gradle and Android SDK
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          .dart_tool
          .packages
          .pub-cache
          ~/.gradle
          /usr/local/lib/android/sdk/licenses
          /usr/local/lib/android/sdk/ndk
          /usr/local/lib/android/sdk/cmake
          /usr/local/lib/android/sdk/platforms
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}-${{ hashFiles('**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Run Android build command
    - name: Build APK
      run: flutter build apk --release

    # Optionally upload the built APK as an artifact of the workflow
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
