name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Checkout the repository to the GitHub Actions runner
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    # Get Flutter SDK
    - name: Install Flutter SDK
      run: |
        sudo snap install flutter --classic
        flutter doctor

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Run Android build command
    - name: Build APK
      run: flutter build apk --release

    # Optionally upload the built APK as an artifact of the workflow
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
